// Code generated by protoc-gen-growrpc. DO NOT EDIT.
package pb_user

import (
	"context"
	"GrowRPC"
	"GrowRPC/xclient"
)

type UserServiceServer interface {
	UserLogin(ctx context.Context, req *UserLoginArgs, resp *UserLoginReply) error
	UserRegister(ctx context.Context, req *UserRegisterArgs, resp *UserRegisterReply) error
	GetUserInfo(ctx context.Context, req *GetUserInfoArgs, resp *GetUserInfoReply) error
	SearchUser(ctx context.Context, req *SearchUserArgs, resp *SearchUserReply) error
	UpdateUserInfo(ctx context.Context, req *UpdateUserInfoArgs, resp *UpdateUserInfoReply) error
}

type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) UserLogin(ctx context.Context, req *UserLoginArgs, resp *UserLoginReply) error {
	return GrowRPC.ErrNotImplemented
}
func (UnimplementedUserServiceServer) UserRegister(ctx context.Context, req *UserRegisterArgs, resp *UserRegisterReply) error {
	return GrowRPC.ErrNotImplemented
}
func (UnimplementedUserServiceServer) GetUserInfo(ctx context.Context, req *GetUserInfoArgs, resp *GetUserInfoReply) error {
	return GrowRPC.ErrNotImplemented
}
func (UnimplementedUserServiceServer) SearchUser(ctx context.Context, req *SearchUserArgs, resp *SearchUserReply) error {
	return GrowRPC.ErrNotImplemented
}
func (UnimplementedUserServiceServer) UpdateUserInfo(ctx context.Context, req *UpdateUserInfoArgs, resp *UpdateUserInfoReply) error {
	return GrowRPC.ErrNotImplemented
}

func RegisterUserServiceServer(server *GrowRPC.Server, impl UserServiceServer) {
	GrowRPC.RegisterMethod[UserLoginArgs, UserLoginReply](server, "UserService.UserLogin", impl.UserLogin)
	GrowRPC.RegisterMethod[UserRegisterArgs, UserRegisterReply](server, "UserService.UserRegister", impl.UserRegister)
	GrowRPC.RegisterMethod[GetUserInfoArgs, GetUserInfoReply](server, "UserService.GetUserInfo", impl.GetUserInfo)
	GrowRPC.RegisterMethod[SearchUserArgs, SearchUserReply](server, "UserService.SearchUser", impl.SearchUser)
	GrowRPC.RegisterMethod[UpdateUserInfoArgs, UpdateUserInfoReply](server, "UserService.UpdateUserInfo", impl.UpdateUserInfo)
}

type UserServiceClient struct {
	xc *xclient.XClient
}

func NewUserServiceClient(xc *xclient.XClient) *UserServiceClient {
	return &UserServiceClient{xc: xc}
}

func (c *UserServiceClient) UserLogin(ctx context.Context, req *UserLoginArgs) (*UserLoginReply, error) {
	resp := &UserLoginReply{}
	err := c.xc.Call(ctx, "UserService.UserLogin", req, resp)
	return resp, err
}
func (c *UserServiceClient) UserRegister(ctx context.Context, req *UserRegisterArgs) (*UserRegisterReply, error) {
	resp := &UserRegisterReply{}
	err := c.xc.Call(ctx, "UserService.UserRegister", req, resp)
	return resp, err
}
func (c *UserServiceClient) GetUserInfo(ctx context.Context, req *GetUserInfoArgs) (*GetUserInfoReply, error) {
	resp := &GetUserInfoReply{}
	err := c.xc.Call(ctx, "UserService.GetUserInfo", req, resp)
	return resp, err
}
func (c *UserServiceClient) SearchUser(ctx context.Context, req *SearchUserArgs) (*SearchUserReply, error) {
	resp := &SearchUserReply{}
	err := c.xc.Call(ctx, "UserService.SearchUser", req, resp)
	return resp, err
}
func (c *UserServiceClient) UpdateUserInfo(ctx context.Context, req *UpdateUserInfoArgs) (*UpdateUserInfoReply, error) {
	resp := &UpdateUserInfoReply{}
	err := c.xc.Call(ctx, "UserService.UpdateUserInfo", req, resp)
	return resp, err
}
