package main

import (
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

func main() {
	protogen.Options{}.Run(func(plugin *protogen.Plugin) error {
		for _, file := range plugin.Files {
			if !file.Generate || len(file.Services) == 0 {
				continue
			}
			generateFile(plugin, file)
		}
		return nil
	})
}

func generateFile(plugin *protogen.Plugin, file *protogen.File) {
	filename := strings.TrimSuffix(file.GeneratedFilenamePrefix, ".pb") + "_growrpc.pb.go"
	g := plugin.NewGeneratedFile(filename, file.GoImportPath)
	pkg := string(file.GoPackageName)

	// --- package + import ---
	g.P("// Code generated by protoc-gen-growrpc. DO NOT EDIT.")
	g.P("package ", pkg)
	g.P()
	g.P("import (")
	g.P("\"context\"")
	g.P("\"GrowRPC\"")
	g.P("\"GrowRPC/xclient\"")
	g.P(")")
	g.P()

	// --- per service ---
	for _, svc := range file.Services {
		sName := svc.GoName

		// Server interface
		g.P("type ", sName, "Server interface {")
		for _, m := range svc.Methods {
			in := "*" + m.Input.GoIdent.GoName
			out := "*" + m.Output.GoIdent.GoName
			g.P(m.GoName, "(ctx context.Context, req ", in, ", resp ", out, ") error")
		}
		g.P("}")
		g.P()

		// Unimplemented
		g.P("type Unimplemented", sName, "Server struct{}")
		for _, m := range svc.Methods {
			in := "*" + m.Input.GoIdent.GoName
			out := "*" + m.Output.GoIdent.GoName
			g.P("func (Unimplemented", sName, "Server) ", m.GoName,
				"(ctx context.Context, req ", in, ", resp ", out, ") error {")
			g.P("return GrowRPC.ErrNotImplemented")
			g.P("}")
		}
		g.P()

		// Register
		g.P("func Register", sName, "Server(server *GrowRPC.Server, impl ", sName, "Server) {")
		for _, m := range svc.Methods {
			in := m.Input.GoIdent.GoName   // "MathArgs" (no star)
			out := m.Output.GoIdent.GoName // "MathReply"
			g.P("GrowRPC.RegisterMethod[", in, ", ", out, "](",
				"server, \"", sName, ".", m.GoName, "\", impl.", m.GoName, ")")
		}
		g.P("}")
		g.P()

		// Client
		g.P("type ", sName, "Client struct {")
		g.P("xc *xclient.XClient")
		g.P("}")
		g.P()
		g.P("func New", sName, "Client(xc *xclient.XClient) *", sName, "Client {")
		g.P("return &", sName, "Client{xc: xc}")
		g.P("}")
		g.P()
		for _, m := range svc.Methods {
			in := "*" + m.Input.GoIdent.GoName
			out := "*" + m.Output.GoIdent.GoName
			baseOut := m.Output.GoIdent.GoName
			g.P("func (c *", sName, "Client) ", m.GoName,
				"(ctx context.Context, req ", in, ") (", out, ", error) {")
			g.P("resp := &", baseOut, "{}")
			g.P("err := c.xc.Call(ctx, \"", sName, ".", m.GoName, "\", req, resp)")
			g.P("return resp, err")
			g.P("}")
		}
		g.P()
	}
}
