// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.20.3
// source: apps/pkg/proto/pb_friend/friend.proto

package pb_friend

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplyFriendArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId int64  `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	ApplyMsg string `protobuf:"bytes,3,opt,name=apply_msg,json=applyMsg,proto3" json:"apply_msg,omitempty"`
}

func (x *ApplyFriendArgs) Reset() {
	*x = ApplyFriendArgs{}
	mi := &file_apps_pkg_proto_pb_friend_friend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyFriendArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyFriendArgs) ProtoMessage() {}

func (x *ApplyFriendArgs) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_friend_friend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyFriendArgs.ProtoReflect.Descriptor instead.
func (*ApplyFriendArgs) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_friend_friend_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyFriendArgs) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ApplyFriendArgs) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *ApplyFriendArgs) GetApplyMsg() string {
	if x != nil {
		return x.ApplyMsg
	}
	return ""
}

type ApplyFriendReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ApplyFriendReply) Reset() {
	*x = ApplyFriendReply{}
	mi := &file_apps_pkg_proto_pb_friend_friend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyFriendReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyFriendReply) ProtoMessage() {}

func (x *ApplyFriendReply) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_friend_friend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyFriendReply.ProtoReflect.Descriptor instead.
func (*ApplyFriendReply) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_friend_friend_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyFriendReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ResolveFriendArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId int64  `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Action   string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"` // "accept" or "reject"
}

func (x *ResolveFriendArgs) Reset() {
	*x = ResolveFriendArgs{}
	mi := &file_apps_pkg_proto_pb_friend_friend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveFriendArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveFriendArgs) ProtoMessage() {}

func (x *ResolveFriendArgs) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_friend_friend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveFriendArgs.ProtoReflect.Descriptor instead.
func (*ResolveFriendArgs) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_friend_friend_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveFriendArgs) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ResolveFriendArgs) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *ResolveFriendArgs) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type ResolveFriendReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ResolveFriendReply) Reset() {
	*x = ResolveFriendReply{}
	mi := &file_apps_pkg_proto_pb_friend_friend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveFriendReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveFriendReply) ProtoMessage() {}

func (x *ResolveFriendReply) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_friend_friend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveFriendReply.ProtoReflect.Descriptor instead.
func (*ResolveFriendReply) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_friend_friend_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveFriendReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetFriendListArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetFriendListArgs) Reset() {
	*x = GetFriendListArgs{}
	mi := &file_apps_pkg_proto_pb_friend_friend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendListArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendListArgs) ProtoMessage() {}

func (x *GetFriendListArgs) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_friend_friend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendListArgs.ProtoReflect.Descriptor instead.
func (*GetFriendListArgs) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_friend_friend_proto_rawDescGZIP(), []int{4}
}

func (x *GetFriendListArgs) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type FriendItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendId int64  `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar   string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Status   int32  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *FriendItem) Reset() {
	*x = FriendItem{}
	mi := &file_apps_pkg_proto_pb_friend_friend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendItem) ProtoMessage() {}

func (x *FriendItem) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_friend_friend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendItem.ProtoReflect.Descriptor instead.
func (*FriendItem) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_friend_friend_proto_rawDescGZIP(), []int{5}
}

func (x *FriendItem) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *FriendItem) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *FriendItem) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *FriendItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetFriendListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Friends []*FriendItem `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
}

func (x *GetFriendListReply) Reset() {
	*x = GetFriendListReply{}
	mi := &file_apps_pkg_proto_pb_friend_friend_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendListReply) ProtoMessage() {}

func (x *GetFriendListReply) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_friend_friend_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendListReply.ProtoReflect.Descriptor instead.
func (*GetFriendListReply) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_friend_friend_proto_rawDescGZIP(), []int{6}
}

func (x *GetFriendListReply) GetFriends() []*FriendItem {
	if x != nil {
		return x.Friends
	}
	return nil
}

type DeleteFriendArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId int64 `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
}

func (x *DeleteFriendArgs) Reset() {
	*x = DeleteFriendArgs{}
	mi := &file_apps_pkg_proto_pb_friend_friend_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFriendArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFriendArgs) ProtoMessage() {}

func (x *DeleteFriendArgs) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_friend_friend_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFriendArgs.ProtoReflect.Descriptor instead.
func (*DeleteFriendArgs) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_friend_friend_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteFriendArgs) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteFriendArgs) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

type DeleteFriendReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteFriendReply) Reset() {
	*x = DeleteFriendReply{}
	mi := &file_apps_pkg_proto_pb_friend_friend_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFriendReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFriendReply) ProtoMessage() {}

func (x *DeleteFriendReply) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_friend_friend_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFriendReply.ProtoReflect.Descriptor instead.
func (*DeleteFriendReply) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_friend_friend_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteFriendReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetPendingRequestsArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetPendingRequestsArgs) Reset() {
	*x = GetPendingRequestsArgs{}
	mi := &file_apps_pkg_proto_pb_friend_friend_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingRequestsArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingRequestsArgs) ProtoMessage() {}

func (x *GetPendingRequestsArgs) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_friend_friend_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingRequestsArgs.ProtoReflect.Descriptor instead.
func (*GetPendingRequestsArgs) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_friend_friend_proto_rawDescGZIP(), []int{9}
}

func (x *GetPendingRequestsArgs) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type PendingRequestItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username  string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname  string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar    string `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	ApplyMsg  string `protobuf:"bytes,5,opt,name=apply_msg,json=applyMsg,proto3" json:"apply_msg,omitempty"`
	CreatedAt string `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *PendingRequestItem) Reset() {
	*x = PendingRequestItem{}
	mi := &file_apps_pkg_proto_pb_friend_friend_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingRequestItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingRequestItem) ProtoMessage() {}

func (x *PendingRequestItem) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_friend_friend_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingRequestItem.ProtoReflect.Descriptor instead.
func (*PendingRequestItem) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_friend_friend_proto_rawDescGZIP(), []int{10}
}

func (x *PendingRequestItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PendingRequestItem) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PendingRequestItem) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PendingRequestItem) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *PendingRequestItem) GetApplyMsg() string {
	if x != nil {
		return x.ApplyMsg
	}
	return ""
}

func (x *PendingRequestItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetPendingRequestsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requests []*PendingRequestItem `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
}

func (x *GetPendingRequestsReply) Reset() {
	*x = GetPendingRequestsReply{}
	mi := &file_apps_pkg_proto_pb_friend_friend_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingRequestsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingRequestsReply) ProtoMessage() {}

func (x *GetPendingRequestsReply) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_friend_friend_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingRequestsReply.ProtoReflect.Descriptor instead.
func (*GetPendingRequestsReply) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_friend_friend_proto_rawDescGZIP(), []int{11}
}

func (x *GetPendingRequestsReply) GetRequests() []*PendingRequestItem {
	if x != nil {
		return x.Requests
	}
	return nil
}

var File_apps_pkg_proto_pb_friend_friend_proto protoreflect.FileDescriptor

var file_apps_pkg_proto_pb_friend_friend_proto_rawDesc = []byte{
	0x0a, 0x25, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x70, 0x62, 0x5f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2f, 0x66, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x62, 0x5f, 0x66, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x22, 0x64, 0x0a, 0x0f, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x41, 0x72, 0x67, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x61,
	0x70, 0x70, 0x6c, 0x79, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x61, 0x70, 0x70, 0x6c, 0x79, 0x4d, 0x73, 0x67, 0x22, 0x2c, 0x0a, 0x10, 0x41, 0x70, 0x70, 0x6c,
	0x79, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x61, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76,
	0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x72, 0x67, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2e, 0x0a, 0x12, 0x52, 0x65, 0x73,
	0x6f, 0x6c, 0x76, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x2c, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x67, 0x73, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x75, 0x0a, 0x0a, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x45,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x2f, 0x0a, 0x07, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x5f, 0x66, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x07, 0x66, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x73, 0x22, 0x48, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x72, 0x67, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x64, 0x22,
	0x2d, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x31,
	0x0a, 0x16, 0x47, 0x65, 0x74, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x73, 0x41, 0x72, 0x67, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x22, 0xb9, 0x01, 0x0a, 0x12, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x4d, 0x73, 0x67, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x54, 0x0a,
	0x17, 0x47, 0x65, 0x74, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x39, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x62, 0x5f,
	0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x73, 0x32, 0x9b, 0x03, 0x0a, 0x0d, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x12, 0x1a, 0x2e, 0x70, 0x62, 0x5f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x72, 0x67, 0x73,
	0x1a, 0x1b, 0x2e, 0x70, 0x62, 0x5f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x41, 0x70, 0x70,
	0x6c, 0x79, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4c, 0x0a,
	0x0d, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x12, 0x1c,
	0x2e, 0x70, 0x62, 0x5f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x6c,
	0x76, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x1d, 0x2e, 0x70,
	0x62, 0x5f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4c, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x2e, 0x70,
	0x62, 0x5f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x1d, 0x2e, 0x70, 0x62, 0x5f,
	0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x49, 0x0a, 0x0c, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x12, 0x1b, 0x2e, 0x70, 0x62, 0x5f, 0x66,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x1c, 0x2e, 0x70, 0x62, 0x5f, 0x66, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x5b, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x50, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x21, 0x2e, 0x70, 0x62, 0x5f,
	0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x22, 0x2e,
	0x70, 0x62, 0x5f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x42, 0x22, 0x5a, 0x20, 0x4e, 0x65, 0x78, 0x75, 0x73, 0x47, 0x6f, 0x2f, 0x61, 0x70, 0x70,
	0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x5f, 0x66,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apps_pkg_proto_pb_friend_friend_proto_rawDescOnce sync.Once
	file_apps_pkg_proto_pb_friend_friend_proto_rawDescData = file_apps_pkg_proto_pb_friend_friend_proto_rawDesc
)

func file_apps_pkg_proto_pb_friend_friend_proto_rawDescGZIP() []byte {
	file_apps_pkg_proto_pb_friend_friend_proto_rawDescOnce.Do(func() {
		file_apps_pkg_proto_pb_friend_friend_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_pkg_proto_pb_friend_friend_proto_rawDescData)
	})
	return file_apps_pkg_proto_pb_friend_friend_proto_rawDescData
}

var file_apps_pkg_proto_pb_friend_friend_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_apps_pkg_proto_pb_friend_friend_proto_goTypes = []any{
	(*ApplyFriendArgs)(nil),         // 0: pb_friend.ApplyFriendArgs
	(*ApplyFriendReply)(nil),        // 1: pb_friend.ApplyFriendReply
	(*ResolveFriendArgs)(nil),       // 2: pb_friend.ResolveFriendArgs
	(*ResolveFriendReply)(nil),      // 3: pb_friend.ResolveFriendReply
	(*GetFriendListArgs)(nil),       // 4: pb_friend.GetFriendListArgs
	(*FriendItem)(nil),              // 5: pb_friend.FriendItem
	(*GetFriendListReply)(nil),      // 6: pb_friend.GetFriendListReply
	(*DeleteFriendArgs)(nil),        // 7: pb_friend.DeleteFriendArgs
	(*DeleteFriendReply)(nil),       // 8: pb_friend.DeleteFriendReply
	(*GetPendingRequestsArgs)(nil),  // 9: pb_friend.GetPendingRequestsArgs
	(*PendingRequestItem)(nil),      // 10: pb_friend.PendingRequestItem
	(*GetPendingRequestsReply)(nil), // 11: pb_friend.GetPendingRequestsReply
}
var file_apps_pkg_proto_pb_friend_friend_proto_depIdxs = []int32{
	5,  // 0: pb_friend.GetFriendListReply.friends:type_name -> pb_friend.FriendItem
	10, // 1: pb_friend.GetPendingRequestsReply.requests:type_name -> pb_friend.PendingRequestItem
	0,  // 2: pb_friend.FriendService.ApplyFriend:input_type -> pb_friend.ApplyFriendArgs
	2,  // 3: pb_friend.FriendService.ResolveFriend:input_type -> pb_friend.ResolveFriendArgs
	4,  // 4: pb_friend.FriendService.GetFriendList:input_type -> pb_friend.GetFriendListArgs
	7,  // 5: pb_friend.FriendService.DeleteFriend:input_type -> pb_friend.DeleteFriendArgs
	9,  // 6: pb_friend.FriendService.GetPendingRequests:input_type -> pb_friend.GetPendingRequestsArgs
	1,  // 7: pb_friend.FriendService.ApplyFriend:output_type -> pb_friend.ApplyFriendReply
	3,  // 8: pb_friend.FriendService.ResolveFriend:output_type -> pb_friend.ResolveFriendReply
	6,  // 9: pb_friend.FriendService.GetFriendList:output_type -> pb_friend.GetFriendListReply
	8,  // 10: pb_friend.FriendService.DeleteFriend:output_type -> pb_friend.DeleteFriendReply
	11, // 11: pb_friend.FriendService.GetPendingRequests:output_type -> pb_friend.GetPendingRequestsReply
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_apps_pkg_proto_pb_friend_friend_proto_init() }
func file_apps_pkg_proto_pb_friend_friend_proto_init() {
	if File_apps_pkg_proto_pb_friend_friend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_pkg_proto_pb_friend_friend_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_pkg_proto_pb_friend_friend_proto_goTypes,
		DependencyIndexes: file_apps_pkg_proto_pb_friend_friend_proto_depIdxs,
		MessageInfos:      file_apps_pkg_proto_pb_friend_friend_proto_msgTypes,
	}.Build()
	File_apps_pkg_proto_pb_friend_friend_proto = out.File
	file_apps_pkg_proto_pb_friend_friend_proto_rawDesc = nil
	file_apps_pkg_proto_pb_friend_friend_proto_goTypes = nil
	file_apps_pkg_proto_pb_friend_friend_proto_depIdxs = nil
}
