// Code generated by protoc-gen-growrpc. DO NOT EDIT.
package pb_friend

import (
	"context"
	"GrowRPC"
	"GrowRPC/xclient"
)

type FriendServiceServer interface {
	ApplyFriend(ctx context.Context, req *ApplyFriendArgs, resp *ApplyFriendReply) error
	ResolveFriend(ctx context.Context, req *ResolveFriendArgs, resp *ResolveFriendReply) error
	GetFriendList(ctx context.Context, req *GetFriendListArgs, resp *GetFriendListReply) error
	DeleteFriend(ctx context.Context, req *DeleteFriendArgs, resp *DeleteFriendReply) error
	GetPendingRequests(ctx context.Context, req *GetPendingRequestsArgs, resp *GetPendingRequestsReply) error
}

type UnimplementedFriendServiceServer struct{}

func (UnimplementedFriendServiceServer) ApplyFriend(ctx context.Context, req *ApplyFriendArgs, resp *ApplyFriendReply) error {
	return GrowRPC.ErrNotImplemented
}
func (UnimplementedFriendServiceServer) ResolveFriend(ctx context.Context, req *ResolveFriendArgs, resp *ResolveFriendReply) error {
	return GrowRPC.ErrNotImplemented
}
func (UnimplementedFriendServiceServer) GetFriendList(ctx context.Context, req *GetFriendListArgs, resp *GetFriendListReply) error {
	return GrowRPC.ErrNotImplemented
}
func (UnimplementedFriendServiceServer) DeleteFriend(ctx context.Context, req *DeleteFriendArgs, resp *DeleteFriendReply) error {
	return GrowRPC.ErrNotImplemented
}
func (UnimplementedFriendServiceServer) GetPendingRequests(ctx context.Context, req *GetPendingRequestsArgs, resp *GetPendingRequestsReply) error {
	return GrowRPC.ErrNotImplemented
}

func RegisterFriendServiceServer(server *GrowRPC.Server, impl FriendServiceServer) {
	GrowRPC.RegisterMethod[ApplyFriendArgs, ApplyFriendReply](server, "FriendService.ApplyFriend", impl.ApplyFriend)
	GrowRPC.RegisterMethod[ResolveFriendArgs, ResolveFriendReply](server, "FriendService.ResolveFriend", impl.ResolveFriend)
	GrowRPC.RegisterMethod[GetFriendListArgs, GetFriendListReply](server, "FriendService.GetFriendList", impl.GetFriendList)
	GrowRPC.RegisterMethod[DeleteFriendArgs, DeleteFriendReply](server, "FriendService.DeleteFriend", impl.DeleteFriend)
	GrowRPC.RegisterMethod[GetPendingRequestsArgs, GetPendingRequestsReply](server, "FriendService.GetPendingRequests", impl.GetPendingRequests)
}

type FriendServiceClient struct {
	xc *xclient.XClient
}

func NewFriendServiceClient(xc *xclient.XClient) *FriendServiceClient {
	return &FriendServiceClient{xc: xc}
}

func (c *FriendServiceClient) ApplyFriend(ctx context.Context, req *ApplyFriendArgs) (*ApplyFriendReply, error) {
	resp := &ApplyFriendReply{}
	err := c.xc.Call(ctx, "FriendService.ApplyFriend", req, resp)
	return resp, err
}
func (c *FriendServiceClient) ResolveFriend(ctx context.Context, req *ResolveFriendArgs) (*ResolveFriendReply, error) {
	resp := &ResolveFriendReply{}
	err := c.xc.Call(ctx, "FriendService.ResolveFriend", req, resp)
	return resp, err
}
func (c *FriendServiceClient) GetFriendList(ctx context.Context, req *GetFriendListArgs) (*GetFriendListReply, error) {
	resp := &GetFriendListReply{}
	err := c.xc.Call(ctx, "FriendService.GetFriendList", req, resp)
	return resp, err
}
func (c *FriendServiceClient) DeleteFriend(ctx context.Context, req *DeleteFriendArgs) (*DeleteFriendReply, error) {
	resp := &DeleteFriendReply{}
	err := c.xc.Call(ctx, "FriendService.DeleteFriend", req, resp)
	return resp, err
}
func (c *FriendServiceClient) GetPendingRequests(ctx context.Context, req *GetPendingRequestsArgs) (*GetPendingRequestsReply, error) {
	resp := &GetPendingRequestsReply{}
	err := c.xc.Call(ctx, "FriendService.GetPendingRequests", req, resp)
	return resp, err
}
