// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.20.3
// source: apps/pkg/proto/pb_msg/msg.proto

package pb_msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 发送消息请求
type SendMessageArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderId   int64  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`       // 发送者id
	ReceiverId int64  `protobuf:"varint,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"` // 接收者id
	Body       string `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`                                // 消息体
	// 网关生成的全局消息 ID（雪花），与 messages.msg_id 一致；为 0 时由 Logic 自行生成（兼容旧客户端）
	MsgId int64 `protobuf:"varint,4,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	// 会话内序号，仅用于同一会话内排序；为 0 表示未使用会话序号
	SeqId int64 `protobuf:"varint,5,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
}

func (x *SendMessageArgs) Reset() {
	*x = SendMessageArgs{}
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageArgs) ProtoMessage() {}

func (x *SendMessageArgs) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageArgs.ProtoReflect.Descriptor instead.
func (*SendMessageArgs) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_msg_msg_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageArgs) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SendMessageArgs) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *SendMessageArgs) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SendMessageArgs) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *SendMessageArgs) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

// 发送消息响应
type SendMessageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId int64 `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
}

func (x *SendMessageReply) Reset() {
	*x = SendMessageReply{}
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageReply) ProtoMessage() {}

func (x *SendMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageReply.ProtoReflect.Descriptor instead.
func (*SendMessageReply) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_msg_msg_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageReply) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

// 同步消息请求
type SyncUnreadArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceiverId int64 `protobuf:"varint,1,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	GroupId    int64 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
}

func (x *SyncUnreadArgs) Reset() {
	*x = SyncUnreadArgs{}
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncUnreadArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUnreadArgs) ProtoMessage() {}

func (x *SyncUnreadArgs) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUnreadArgs.ProtoReflect.Descriptor instead.
func (*SyncUnreadArgs) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_msg_msg_proto_rawDescGZIP(), []int{2}
}

func (x *SyncUnreadArgs) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *SyncUnreadArgs) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// 同步消息响应
type SyncUnreadReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 定义一个消息体列表
	Messages []*MessageItem `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *SyncUnreadReply) Reset() {
	*x = SyncUnreadReply{}
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncUnreadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUnreadReply) ProtoMessage() {}

func (x *SyncUnreadReply) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUnreadReply.ProtoReflect.Descriptor instead.
func (*SyncUnreadReply) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_msg_msg_proto_rawDescGZIP(), []int{3}
}

func (x *SyncUnreadReply) GetMessages() []*MessageItem {
	if x != nil {
		return x.Messages
	}
	return nil
}

// 消息体
type MessageItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId      int64  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	SenderId   int64  `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	GroupId    int64  `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Content    string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreateTime string `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	SeqId      int64  `protobuf:"varint,6,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	// 发送状态：0 未发送 1 发送未确认 2 发送已确认（与 models 常量一致）
	SendStatus int32 `protobuf:"varint,7,opt,name=send_status,json=sendStatus,proto3" json:"send_status,omitempty"`
}

func (x *MessageItem) Reset() {
	*x = MessageItem{}
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageItem) ProtoMessage() {}

func (x *MessageItem) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageItem.ProtoReflect.Descriptor instead.
func (*MessageItem) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_msg_msg_proto_rawDescGZIP(), []int{4}
}

func (x *MessageItem) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *MessageItem) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *MessageItem) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *MessageItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageItem) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *MessageItem) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *MessageItem) GetSendStatus() int32 {
	if x != nil {
		return x.SendStatus
	}
	return 0
}

// 网关：对端 WS 已成功写入后上报，将 send_status 0 -> 1
type NotifyDeliveredArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId int64 `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
}

func (x *NotifyDeliveredArgs) Reset() {
	*x = NotifyDeliveredArgs{}
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyDeliveredArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyDeliveredArgs) ProtoMessage() {}

func (x *NotifyDeliveredArgs) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyDeliveredArgs.ProtoReflect.Descriptor instead.
func (*NotifyDeliveredArgs) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_msg_msg_proto_rawDescGZIP(), []int{5}
}

func (x *NotifyDeliveredArgs) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

type NotifyDeliveredReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *NotifyDeliveredReply) Reset() {
	*x = NotifyDeliveredReply{}
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyDeliveredReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyDeliveredReply) ProtoMessage() {}

func (x *NotifyDeliveredReply) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyDeliveredReply.ProtoReflect.Descriptor instead.
func (*NotifyDeliveredReply) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_msg_msg_proto_rawDescGZIP(), []int{6}
}

func (x *NotifyDeliveredReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 读消息列表请求
type ReadMessagesArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceiverId int64 `protobuf:"varint,1,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"` // 谁读了消息
}

func (x *ReadMessagesArgs) Reset() {
	*x = ReadMessagesArgs{}
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMessagesArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMessagesArgs) ProtoMessage() {}

func (x *ReadMessagesArgs) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMessagesArgs.ProtoReflect.Descriptor instead.
func (*ReadMessagesArgs) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_msg_msg_proto_rawDescGZIP(), []int{7}
}

func (x *ReadMessagesArgs) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

// 读消息列表响应
type ReadMessagesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 返回个 true 就行
}

func (x *ReadMessagesReply) Reset() {
	*x = ReadMessagesReply{}
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMessagesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMessagesReply) ProtoMessage() {}

func (x *ReadMessagesReply) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMessagesReply.ProtoReflect.Descriptor instead.
func (*ReadMessagesReply) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_msg_msg_proto_rawDescGZIP(), []int{8}
}

func (x *ReadMessagesReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 读消息ACK
type AckMessageArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId int64 `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
}

func (x *AckMessageArgs) Reset() {
	*x = AckMessageArgs{}
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMessageArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMessageArgs) ProtoMessage() {}

func (x *AckMessageArgs) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMessageArgs.ProtoReflect.Descriptor instead.
func (*AckMessageArgs) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_msg_msg_proto_rawDescGZIP(), []int{9}
}

func (x *AckMessageArgs) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

type AckMessageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *AckMessageReply) Reset() {
	*x = AckMessageReply{}
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMessageReply) ProtoMessage() {}

func (x *AckMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMessageReply.ProtoReflect.Descriptor instead.
func (*AckMessageReply) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_msg_msg_proto_rawDescGZIP(), []int{10}
}

func (x *AckMessageReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetConversationsArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetConversationsArgs) Reset() {
	*x = GetConversationsArgs{}
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationsArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationsArgs) ProtoMessage() {}

func (x *GetConversationsArgs) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationsArgs.ProtoReflect.Descriptor instead.
func (*GetConversationsArgs) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_msg_msg_proto_rawDescGZIP(), []int{11}
}

func (x *GetConversationsArgs) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ConversationItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetId    int64 `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	SessionType int32 `protobuf:"varint,2,opt,name=session_type,json=sessionType,proto3" json:"session_type,omitempty"` // 1: 单聊, 2: 群聊
	UnreadCount int64 `protobuf:"varint,3,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	OwnerId     int64 `protobuf:"varint,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
}

func (x *ConversationItem) Reset() {
	*x = ConversationItem{}
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationItem) ProtoMessage() {}

func (x *ConversationItem) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationItem.ProtoReflect.Descriptor instead.
func (*ConversationItem) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_msg_msg_proto_rawDescGZIP(), []int{12}
}

func (x *ConversationItem) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *ConversationItem) GetSessionType() int32 {
	if x != nil {
		return x.SessionType
	}
	return 0
}

func (x *ConversationItem) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *ConversationItem) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

type GetConversationsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Conversations []*ConversationItem `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
}

func (x *GetConversationsReply) Reset() {
	*x = GetConversationsReply{}
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationsReply) ProtoMessage() {}

func (x *GetConversationsReply) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationsReply.ProtoReflect.Descriptor instead.
func (*GetConversationsReply) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_msg_msg_proto_rawDescGZIP(), []int{13}
}

func (x *GetConversationsReply) GetConversations() []*ConversationItem {
	if x != nil {
		return x.Conversations
	}
	return nil
}

type GetChatHistoryArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetId int64 `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Cursor   int64 `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit    int64 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetChatHistoryArgs) Reset() {
	*x = GetChatHistoryArgs{}
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryArgs) ProtoMessage() {}

func (x *GetChatHistoryArgs) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryArgs.ProtoReflect.Descriptor instead.
func (*GetChatHistoryArgs) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_msg_msg_proto_rawDescGZIP(), []int{14}
}

func (x *GetChatHistoryArgs) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetChatHistoryArgs) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *GetChatHistoryArgs) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *GetChatHistoryArgs) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetChatHistoryReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages   []*MessageItem `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	NextCursor int64          `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore    bool           `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	TargetId   int64          `protobuf:"varint,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
}

func (x *GetChatHistoryReply) Reset() {
	*x = GetChatHistoryReply{}
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryReply) ProtoMessage() {}

func (x *GetChatHistoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryReply.ProtoReflect.Descriptor instead.
func (*GetChatHistoryReply) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_msg_msg_proto_rawDescGZIP(), []int{15}
}

func (x *GetChatHistoryReply) GetMessages() []*MessageItem {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetChatHistoryReply) GetNextCursor() int64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *GetChatHistoryReply) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetChatHistoryReply) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type MarkReadArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetId      int64 `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	LastReadMsgId int64 `protobuf:"varint,3,opt,name=last_read_msg_id,json=lastReadMsgId,proto3" json:"last_read_msg_id,omitempty"`
	SessionType   int32 `protobuf:"varint,4,opt,name=session_type,json=sessionType,proto3" json:"session_type,omitempty"`
}

func (x *MarkReadArgs) Reset() {
	*x = MarkReadArgs{}
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadArgs) ProtoMessage() {}

func (x *MarkReadArgs) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadArgs.ProtoReflect.Descriptor instead.
func (*MarkReadArgs) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_msg_msg_proto_rawDescGZIP(), []int{16}
}

func (x *MarkReadArgs) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MarkReadArgs) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *MarkReadArgs) GetLastReadMsgId() int64 {
	if x != nil {
		return x.LastReadMsgId
	}
	return 0
}

func (x *MarkReadArgs) GetSessionType() int32 {
	if x != nil {
		return x.SessionType
	}
	return 0
}

type MarkReadReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *MarkReadReply) Reset() {
	*x = MarkReadReply{}
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadReply) ProtoMessage() {}

func (x *MarkReadReply) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_msg_msg_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadReply.ProtoReflect.Descriptor instead.
func (*MarkReadReply) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_msg_msg_proto_rawDescGZIP(), []int{17}
}

func (x *MarkReadReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_apps_pkg_proto_pb_msg_msg_proto protoreflect.FileDescriptor

var file_apps_pkg_proto_pb_msg_msg_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x22, 0x91, 0x01, 0x0a, 0x0f, 0x53, 0x65,
	0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x41, 0x72, 0x67, 0x73, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12,
	0x15, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x65, 0x71, 0x5f, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x65, 0x71, 0x49, 0x64, 0x22, 0x29, 0x0a,
	0x10, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x0e, 0x53, 0x79, 0x6e, 0x63,
	0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x41, 0x72, 0x67, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x42, 0x0a, 0x0f, 0x53, 0x79, 0x6e, 0x63, 0x55, 0x6e,
	0x72, 0x65, 0x61, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2f, 0x0a, 0x08, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62,
	0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0xcf, 0x01, 0x0a, 0x0b, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x73,
	0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x65, 0x71, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73,
	0x65, 0x6e, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2c, 0x0a, 0x13,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64, 0x41,
	0x72, 0x67, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x22, 0x30, 0x0a, 0x14, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x33, 0x0a, 0x10,
	0x52, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x41, 0x72, 0x67, 0x73,
	0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x2d, 0x0a, 0x11, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x22, 0x27, 0x0a, 0x0e, 0x41, 0x63, 0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x41, 0x72,
	0x67, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x22, 0x2b, 0x0a, 0x0f, 0x41, 0x63, 0x6b,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x2f, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e,
	0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x41, 0x72, 0x67, 0x73, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x90, 0x01, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x76,
	0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1b, 0x0a, 0x09,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x75, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x22, 0x57, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x3e, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x5f,
	0x6d, 0x73, 0x67, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x22, 0x78, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x41, 0x72, 0x67, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x9f, 0x01,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2f, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x63,
	0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6e, 0x65, 0x78,
	0x74, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x61, 0x73, 0x5f, 0x6d,
	0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x61, 0x73, 0x4d, 0x6f,
	0x72, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x22,
	0x90, 0x01, 0x0a, 0x0c, 0x4d, 0x61, 0x72, 0x6b, 0x52, 0x65, 0x61, 0x64, 0x41, 0x72, 0x67, 0x73,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x72,
	0x65, 0x61, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12,
	0x21, 0x0a, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x29, 0x0a, 0x0d, 0x4d, 0x61, 0x72, 0x6b, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0xf9, 0x03,
	0x0a, 0x0a, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0a,
	0x53, 0x79, 0x6e, 0x63, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x5f,
	0x6d, 0x73, 0x67, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x41, 0x72,
	0x67, 0x73, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x79, 0x6e, 0x63,
	0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4c, 0x0a, 0x0f, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64, 0x12, 0x1b,
	0x2e, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x44, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x1c, 0x2e, 0x70, 0x62,
	0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x44, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3d, 0x0a, 0x0a, 0x41, 0x63, 0x6b,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67,
	0x2e, 0x41, 0x63, 0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x41, 0x72, 0x67, 0x73, 0x1a,
	0x17, 0x2e, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x41, 0x63, 0x6b, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x43, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x5f, 0x6d, 0x73,
	0x67, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x41, 0x72,
	0x67, 0x73, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x52, 0x65, 0x61, 0x64,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4f, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x1c, 0x2e, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x41, 0x72, 0x67, 0x73, 0x1a,
	0x1d, 0x2e, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x76,
	0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x49,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x12, 0x1a, 0x2e, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61,
	0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x1b, 0x2e, 0x70,
	0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3e, 0x0a, 0x0f, 0x4d, 0x61, 0x72,
	0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x61, 0x64, 0x12, 0x14, 0x2e, 0x70,
	0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x52, 0x65, 0x61, 0x64, 0x41, 0x72,
	0x67, 0x73, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x61, 0x72, 0x6b,
	0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x1f, 0x5a, 0x1d, 0x4e, 0x65, 0x78,
	0x75, 0x73, 0x47, 0x6f, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_apps_pkg_proto_pb_msg_msg_proto_rawDescOnce sync.Once
	file_apps_pkg_proto_pb_msg_msg_proto_rawDescData = file_apps_pkg_proto_pb_msg_msg_proto_rawDesc
)

func file_apps_pkg_proto_pb_msg_msg_proto_rawDescGZIP() []byte {
	file_apps_pkg_proto_pb_msg_msg_proto_rawDescOnce.Do(func() {
		file_apps_pkg_proto_pb_msg_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_pkg_proto_pb_msg_msg_proto_rawDescData)
	})
	return file_apps_pkg_proto_pb_msg_msg_proto_rawDescData
}

var file_apps_pkg_proto_pb_msg_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_apps_pkg_proto_pb_msg_msg_proto_goTypes = []any{
	(*SendMessageArgs)(nil),       // 0: pb_msg.SendMessageArgs
	(*SendMessageReply)(nil),      // 1: pb_msg.SendMessageReply
	(*SyncUnreadArgs)(nil),        // 2: pb_msg.SyncUnreadArgs
	(*SyncUnreadReply)(nil),       // 3: pb_msg.SyncUnreadReply
	(*MessageItem)(nil),           // 4: pb_msg.MessageItem
	(*NotifyDeliveredArgs)(nil),   // 5: pb_msg.NotifyDeliveredArgs
	(*NotifyDeliveredReply)(nil),  // 6: pb_msg.NotifyDeliveredReply
	(*ReadMessagesArgs)(nil),      // 7: pb_msg.ReadMessagesArgs
	(*ReadMessagesReply)(nil),     // 8: pb_msg.ReadMessagesReply
	(*AckMessageArgs)(nil),        // 9: pb_msg.AckMessageArgs
	(*AckMessageReply)(nil),       // 10: pb_msg.AckMessageReply
	(*GetConversationsArgs)(nil),  // 11: pb_msg.GetConversationsArgs
	(*ConversationItem)(nil),      // 12: pb_msg.ConversationItem
	(*GetConversationsReply)(nil), // 13: pb_msg.GetConversationsReply
	(*GetChatHistoryArgs)(nil),    // 14: pb_msg.GetChatHistoryArgs
	(*GetChatHistoryReply)(nil),   // 15: pb_msg.GetChatHistoryReply
	(*MarkReadArgs)(nil),          // 16: pb_msg.MarkReadArgs
	(*MarkReadReply)(nil),         // 17: pb_msg.MarkReadReply
}
var file_apps_pkg_proto_pb_msg_msg_proto_depIdxs = []int32{
	4,  // 0: pb_msg.SyncUnreadReply.messages:type_name -> pb_msg.MessageItem
	12, // 1: pb_msg.GetConversationsReply.conversations:type_name -> pb_msg.ConversationItem
	4,  // 2: pb_msg.GetChatHistoryReply.messages:type_name -> pb_msg.MessageItem
	2,  // 3: pb_msg.MsgService.SyncUnread:input_type -> pb_msg.SyncUnreadArgs
	5,  // 4: pb_msg.MsgService.NotifyDelivered:input_type -> pb_msg.NotifyDeliveredArgs
	9,  // 5: pb_msg.MsgService.AckMessage:input_type -> pb_msg.AckMessageArgs
	7,  // 6: pb_msg.MsgService.ReadMessages:input_type -> pb_msg.ReadMessagesArgs
	11, // 7: pb_msg.MsgService.GetConversations:input_type -> pb_msg.GetConversationsArgs
	14, // 8: pb_msg.MsgService.GetChatHistory:input_type -> pb_msg.GetChatHistoryArgs
	16, // 9: pb_msg.MsgService.MarkMessageRead:input_type -> pb_msg.MarkReadArgs
	3,  // 10: pb_msg.MsgService.SyncUnread:output_type -> pb_msg.SyncUnreadReply
	6,  // 11: pb_msg.MsgService.NotifyDelivered:output_type -> pb_msg.NotifyDeliveredReply
	10, // 12: pb_msg.MsgService.AckMessage:output_type -> pb_msg.AckMessageReply
	8,  // 13: pb_msg.MsgService.ReadMessages:output_type -> pb_msg.ReadMessagesReply
	13, // 14: pb_msg.MsgService.GetConversations:output_type -> pb_msg.GetConversationsReply
	15, // 15: pb_msg.MsgService.GetChatHistory:output_type -> pb_msg.GetChatHistoryReply
	17, // 16: pb_msg.MsgService.MarkMessageRead:output_type -> pb_msg.MarkReadReply
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_apps_pkg_proto_pb_msg_msg_proto_init() }
func file_apps_pkg_proto_pb_msg_msg_proto_init() {
	if File_apps_pkg_proto_pb_msg_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_pkg_proto_pb_msg_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_pkg_proto_pb_msg_msg_proto_goTypes,
		DependencyIndexes: file_apps_pkg_proto_pb_msg_msg_proto_depIdxs,
		MessageInfos:      file_apps_pkg_proto_pb_msg_msg_proto_msgTypes,
	}.Build()
	File_apps_pkg_proto_pb_msg_msg_proto = out.File
	file_apps_pkg_proto_pb_msg_msg_proto_rawDesc = nil
	file_apps_pkg_proto_pb_msg_msg_proto_goTypes = nil
	file_apps_pkg_proto_pb_msg_msg_proto_depIdxs = nil
}
