// Code generated by protoc-gen-growrpc. DO NOT EDIT.
package pb_msg

import (
	"context"
	"GrowRPC"
	"GrowRPC/xclient"
)

type MsgServiceServer interface {
	SyncUnread(ctx context.Context, req *SyncUnreadArgs, resp *SyncUnreadReply) error
	NotifyDelivered(ctx context.Context, req *NotifyDeliveredArgs, resp *NotifyDeliveredReply) error
	AckMessage(ctx context.Context, req *AckMessageArgs, resp *AckMessageReply) error
	ReadMessages(ctx context.Context, req *ReadMessagesArgs, resp *ReadMessagesReply) error
	GetConversations(ctx context.Context, req *GetConversationsArgs, resp *GetConversationsReply) error
	GetChatHistory(ctx context.Context, req *GetChatHistoryArgs, resp *GetChatHistoryReply) error
	MarkMessageRead(ctx context.Context, req *MarkReadArgs, resp *MarkReadReply) error
}

type UnimplementedMsgServiceServer struct{}

func (UnimplementedMsgServiceServer) SyncUnread(ctx context.Context, req *SyncUnreadArgs, resp *SyncUnreadReply) error {
	return GrowRPC.ErrNotImplemented
}
func (UnimplementedMsgServiceServer) NotifyDelivered(ctx context.Context, req *NotifyDeliveredArgs, resp *NotifyDeliveredReply) error {
	return GrowRPC.ErrNotImplemented
}
func (UnimplementedMsgServiceServer) AckMessage(ctx context.Context, req *AckMessageArgs, resp *AckMessageReply) error {
	return GrowRPC.ErrNotImplemented
}
func (UnimplementedMsgServiceServer) ReadMessages(ctx context.Context, req *ReadMessagesArgs, resp *ReadMessagesReply) error {
	return GrowRPC.ErrNotImplemented
}
func (UnimplementedMsgServiceServer) GetConversations(ctx context.Context, req *GetConversationsArgs, resp *GetConversationsReply) error {
	return GrowRPC.ErrNotImplemented
}
func (UnimplementedMsgServiceServer) GetChatHistory(ctx context.Context, req *GetChatHistoryArgs, resp *GetChatHistoryReply) error {
	return GrowRPC.ErrNotImplemented
}
func (UnimplementedMsgServiceServer) MarkMessageRead(ctx context.Context, req *MarkReadArgs, resp *MarkReadReply) error {
	return GrowRPC.ErrNotImplemented
}

func RegisterMsgServiceServer(server *GrowRPC.Server, impl MsgServiceServer) {
	GrowRPC.RegisterMethod[SyncUnreadArgs, SyncUnreadReply](server, "MsgService.SyncUnread", impl.SyncUnread)
	GrowRPC.RegisterMethod[NotifyDeliveredArgs, NotifyDeliveredReply](server, "MsgService.NotifyDelivered", impl.NotifyDelivered)
	GrowRPC.RegisterMethod[AckMessageArgs, AckMessageReply](server, "MsgService.AckMessage", impl.AckMessage)
	GrowRPC.RegisterMethod[ReadMessagesArgs, ReadMessagesReply](server, "MsgService.ReadMessages", impl.ReadMessages)
	GrowRPC.RegisterMethod[GetConversationsArgs, GetConversationsReply](server, "MsgService.GetConversations", impl.GetConversations)
	GrowRPC.RegisterMethod[GetChatHistoryArgs, GetChatHistoryReply](server, "MsgService.GetChatHistory", impl.GetChatHistory)
	GrowRPC.RegisterMethod[MarkReadArgs, MarkReadReply](server, "MsgService.MarkMessageRead", impl.MarkMessageRead)
}

type MsgServiceClient struct {
	xc *xclient.XClient
}

func NewMsgServiceClient(xc *xclient.XClient) *MsgServiceClient {
	return &MsgServiceClient{xc: xc}
}

func (c *MsgServiceClient) SyncUnread(ctx context.Context, req *SyncUnreadArgs) (*SyncUnreadReply, error) {
	resp := &SyncUnreadReply{}
	err := c.xc.Call(ctx, "MsgService.SyncUnread", req, resp)
	return resp, err
}
func (c *MsgServiceClient) NotifyDelivered(ctx context.Context, req *NotifyDeliveredArgs) (*NotifyDeliveredReply, error) {
	resp := &NotifyDeliveredReply{}
	err := c.xc.Call(ctx, "MsgService.NotifyDelivered", req, resp)
	return resp, err
}
func (c *MsgServiceClient) AckMessage(ctx context.Context, req *AckMessageArgs) (*AckMessageReply, error) {
	resp := &AckMessageReply{}
	err := c.xc.Call(ctx, "MsgService.AckMessage", req, resp)
	return resp, err
}
func (c *MsgServiceClient) ReadMessages(ctx context.Context, req *ReadMessagesArgs) (*ReadMessagesReply, error) {
	resp := &ReadMessagesReply{}
	err := c.xc.Call(ctx, "MsgService.ReadMessages", req, resp)
	return resp, err
}
func (c *MsgServiceClient) GetConversations(ctx context.Context, req *GetConversationsArgs) (*GetConversationsReply, error) {
	resp := &GetConversationsReply{}
	err := c.xc.Call(ctx, "MsgService.GetConversations", req, resp)
	return resp, err
}
func (c *MsgServiceClient) GetChatHistory(ctx context.Context, req *GetChatHistoryArgs) (*GetChatHistoryReply, error) {
	resp := &GetChatHistoryReply{}
	err := c.xc.Call(ctx, "MsgService.GetChatHistory", req, resp)
	return resp, err
}
func (c *MsgServiceClient) MarkMessageRead(ctx context.Context, req *MarkReadArgs) (*MarkReadReply, error) {
	resp := &MarkReadReply{}
	err := c.xc.Call(ctx, "MsgService.MarkMessageRead", req, resp)
	return resp, err
}
