// Code generated by protoc-gen-growrpc. DO NOT EDIT.
package pb_group

import (
	"context"
	"GrowRPC"
	"GrowRPC/xclient"
)

type GroupServiceServer interface {
	CreateGroup(ctx context.Context, req *CreateGroupArgs, resp *CreateGroupReply) error
	GetGroupList(ctx context.Context, req *GetGroupListArgs, resp *GetGroupListReply) error
	GetGroupInfo(ctx context.Context, req *GetGroupInfoArgs, resp *GetGroupInfoReply) error
	GetGroupMembers(ctx context.Context, req *GetGroupMembersArgs, resp *GetGroupMembersReply) error
	JoinGroup(ctx context.Context, req *JoinGroupArgs, resp *JoinGroupReply) error
	LeaveGroup(ctx context.Context, req *LeaveGroupArgs, resp *LeaveGroupReply) error
	GetGroupHistory(ctx context.Context, req *GetGroupHistoryArgs, resp *GetGroupHistoryReply) error
	DissolveGroup(ctx context.Context, req *DissolveGroupArgs, resp *DissolveGroupReply) error
}

type UnimplementedGroupServiceServer struct{}

func (UnimplementedGroupServiceServer) CreateGroup(ctx context.Context, req *CreateGroupArgs, resp *CreateGroupReply) error {
	return GrowRPC.ErrNotImplemented
}
func (UnimplementedGroupServiceServer) GetGroupList(ctx context.Context, req *GetGroupListArgs, resp *GetGroupListReply) error {
	return GrowRPC.ErrNotImplemented
}
func (UnimplementedGroupServiceServer) GetGroupInfo(ctx context.Context, req *GetGroupInfoArgs, resp *GetGroupInfoReply) error {
	return GrowRPC.ErrNotImplemented
}
func (UnimplementedGroupServiceServer) GetGroupMembers(ctx context.Context, req *GetGroupMembersArgs, resp *GetGroupMembersReply) error {
	return GrowRPC.ErrNotImplemented
}
func (UnimplementedGroupServiceServer) JoinGroup(ctx context.Context, req *JoinGroupArgs, resp *JoinGroupReply) error {
	return GrowRPC.ErrNotImplemented
}
func (UnimplementedGroupServiceServer) LeaveGroup(ctx context.Context, req *LeaveGroupArgs, resp *LeaveGroupReply) error {
	return GrowRPC.ErrNotImplemented
}
func (UnimplementedGroupServiceServer) GetGroupHistory(ctx context.Context, req *GetGroupHistoryArgs, resp *GetGroupHistoryReply) error {
	return GrowRPC.ErrNotImplemented
}
func (UnimplementedGroupServiceServer) DissolveGroup(ctx context.Context, req *DissolveGroupArgs, resp *DissolveGroupReply) error {
	return GrowRPC.ErrNotImplemented
}

func RegisterGroupServiceServer(server *GrowRPC.Server, impl GroupServiceServer) {
	GrowRPC.RegisterMethod[CreateGroupArgs, CreateGroupReply](server, "GroupService.CreateGroup", impl.CreateGroup)
	GrowRPC.RegisterMethod[GetGroupListArgs, GetGroupListReply](server, "GroupService.GetGroupList", impl.GetGroupList)
	GrowRPC.RegisterMethod[GetGroupInfoArgs, GetGroupInfoReply](server, "GroupService.GetGroupInfo", impl.GetGroupInfo)
	GrowRPC.RegisterMethod[GetGroupMembersArgs, GetGroupMembersReply](server, "GroupService.GetGroupMembers", impl.GetGroupMembers)
	GrowRPC.RegisterMethod[JoinGroupArgs, JoinGroupReply](server, "GroupService.JoinGroup", impl.JoinGroup)
	GrowRPC.RegisterMethod[LeaveGroupArgs, LeaveGroupReply](server, "GroupService.LeaveGroup", impl.LeaveGroup)
	GrowRPC.RegisterMethod[GetGroupHistoryArgs, GetGroupHistoryReply](server, "GroupService.GetGroupHistory", impl.GetGroupHistory)
	GrowRPC.RegisterMethod[DissolveGroupArgs, DissolveGroupReply](server, "GroupService.DissolveGroup", impl.DissolveGroup)
}

type GroupServiceClient struct {
	xc *xclient.XClient
}

func NewGroupServiceClient(xc *xclient.XClient) *GroupServiceClient {
	return &GroupServiceClient{xc: xc}
}

func (c *GroupServiceClient) CreateGroup(ctx context.Context, req *CreateGroupArgs) (*CreateGroupReply, error) {
	resp := &CreateGroupReply{}
	err := c.xc.Call(ctx, "GroupService.CreateGroup", req, resp)
	return resp, err
}
func (c *GroupServiceClient) GetGroupList(ctx context.Context, req *GetGroupListArgs) (*GetGroupListReply, error) {
	resp := &GetGroupListReply{}
	err := c.xc.Call(ctx, "GroupService.GetGroupList", req, resp)
	return resp, err
}
func (c *GroupServiceClient) GetGroupInfo(ctx context.Context, req *GetGroupInfoArgs) (*GetGroupInfoReply, error) {
	resp := &GetGroupInfoReply{}
	err := c.xc.Call(ctx, "GroupService.GetGroupInfo", req, resp)
	return resp, err
}
func (c *GroupServiceClient) GetGroupMembers(ctx context.Context, req *GetGroupMembersArgs) (*GetGroupMembersReply, error) {
	resp := &GetGroupMembersReply{}
	err := c.xc.Call(ctx, "GroupService.GetGroupMembers", req, resp)
	return resp, err
}
func (c *GroupServiceClient) JoinGroup(ctx context.Context, req *JoinGroupArgs) (*JoinGroupReply, error) {
	resp := &JoinGroupReply{}
	err := c.xc.Call(ctx, "GroupService.JoinGroup", req, resp)
	return resp, err
}
func (c *GroupServiceClient) LeaveGroup(ctx context.Context, req *LeaveGroupArgs) (*LeaveGroupReply, error) {
	resp := &LeaveGroupReply{}
	err := c.xc.Call(ctx, "GroupService.LeaveGroup", req, resp)
	return resp, err
}
func (c *GroupServiceClient) GetGroupHistory(ctx context.Context, req *GetGroupHistoryArgs) (*GetGroupHistoryReply, error) {
	resp := &GetGroupHistoryReply{}
	err := c.xc.Call(ctx, "GroupService.GetGroupHistory", req, resp)
	return resp, err
}
func (c *GroupServiceClient) DissolveGroup(ctx context.Context, req *DissolveGroupArgs) (*DissolveGroupReply, error) {
	resp := &DissolveGroupReply{}
	err := c.xc.Call(ctx, "GroupService.DissolveGroup", req, resp)
	return resp, err
}
