// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.20.3
// source: apps/pkg/proto/pb_group/group.proto

package pb_group

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGroupArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int64   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupName string  `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	MemberIds []int64 `protobuf:"varint,3,rep,packed,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
}

func (x *CreateGroupArgs) Reset() {
	*x = CreateGroupArgs{}
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupArgs) ProtoMessage() {}

func (x *CreateGroupArgs) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupArgs.ProtoReflect.Descriptor instead.
func (*CreateGroupArgs) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_group_group_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGroupArgs) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateGroupArgs) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *CreateGroupArgs) GetMemberIds() []int64 {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

type CreateGroupReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId int64 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
}

func (x *CreateGroupReply) Reset() {
	*x = CreateGroupReply{}
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupReply) ProtoMessage() {}

func (x *CreateGroupReply) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupReply.ProtoReflect.Descriptor instead.
func (*CreateGroupReply) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_group_group_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGroupReply) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GetGroupListArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetGroupListArgs) Reset() {
	*x = GetGroupListArgs{}
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupListArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupListArgs) ProtoMessage() {}

func (x *GetGroupListArgs) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupListArgs.ProtoReflect.Descriptor instead.
func (*GetGroupListArgs) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_group_group_proto_rawDescGZIP(), []int{2}
}

func (x *GetGroupListArgs) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GroupItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId   int64  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupName string `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	OwnerId   int64  `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
}

func (x *GroupItem) Reset() {
	*x = GroupItem{}
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupItem) ProtoMessage() {}

func (x *GroupItem) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupItem.ProtoReflect.Descriptor instead.
func (*GroupItem) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_group_group_proto_rawDescGZIP(), []int{3}
}

func (x *GroupItem) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupItem) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupItem) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

type GetGroupListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groups []*GroupItem `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
}

func (x *GetGroupListReply) Reset() {
	*x = GetGroupListReply{}
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupListReply) ProtoMessage() {}

func (x *GetGroupListReply) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupListReply.ProtoReflect.Descriptor instead.
func (*GetGroupListReply) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_group_group_proto_rawDescGZIP(), []int{4}
}

func (x *GetGroupListReply) GetGroups() []*GroupItem {
	if x != nil {
		return x.Groups
	}
	return nil
}

type GetGroupInfoArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId int64 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
}

func (x *GetGroupInfoArgs) Reset() {
	*x = GetGroupInfoArgs{}
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupInfoArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupInfoArgs) ProtoMessage() {}

func (x *GetGroupInfoArgs) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupInfoArgs.ProtoReflect.Descriptor instead.
func (*GetGroupInfoArgs) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_group_group_proto_rawDescGZIP(), []int{5}
}

func (x *GetGroupInfoArgs) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GetGroupInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId   int64  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupName string `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	OwnerId   int64  `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
}

func (x *GetGroupInfoReply) Reset() {
	*x = GetGroupInfoReply{}
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupInfoReply) ProtoMessage() {}

func (x *GetGroupInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupInfoReply.ProtoReflect.Descriptor instead.
func (*GetGroupInfoReply) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_group_group_proto_rawDescGZIP(), []int{6}
}

func (x *GetGroupInfoReply) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetGroupInfoReply) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GetGroupInfoReply) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

type GetGroupMembersArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId int64 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
}

func (x *GetGroupMembersArgs) Reset() {
	*x = GetGroupMembersArgs{}
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMembersArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMembersArgs) ProtoMessage() {}

func (x *GetGroupMembersArgs) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMembersArgs.ProtoReflect.Descriptor instead.
func (*GetGroupMembersArgs) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_group_group_proto_rawDescGZIP(), []int{7}
}

func (x *GetGroupMembersArgs) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GroupMemberItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role     int32  `protobuf:"varint,2,opt,name=role,proto3" json:"role,omitempty"`
	Nickname string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
}

func (x *GroupMemberItem) Reset() {
	*x = GroupMemberItem{}
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberItem) ProtoMessage() {}

func (x *GroupMemberItem) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberItem.ProtoReflect.Descriptor instead.
func (*GroupMemberItem) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_group_group_proto_rawDescGZIP(), []int{8}
}

func (x *GroupMemberItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupMemberItem) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *GroupMemberItem) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type GetGroupMembersReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members []*GroupMemberItem `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *GetGroupMembersReply) Reset() {
	*x = GetGroupMembersReply{}
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMembersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMembersReply) ProtoMessage() {}

func (x *GetGroupMembersReply) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMembersReply.ProtoReflect.Descriptor instead.
func (*GetGroupMembersReply) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_group_group_proto_rawDescGZIP(), []int{9}
}

func (x *GetGroupMembersReply) GetMembers() []*GroupMemberItem {
	if x != nil {
		return x.Members
	}
	return nil
}

type JoinGroupArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId int64 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
}

func (x *JoinGroupArgs) Reset() {
	*x = JoinGroupArgs{}
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGroupArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupArgs) ProtoMessage() {}

func (x *JoinGroupArgs) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupArgs.ProtoReflect.Descriptor instead.
func (*JoinGroupArgs) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_group_group_proto_rawDescGZIP(), []int{10}
}

func (x *JoinGroupArgs) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *JoinGroupArgs) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type JoinGroupReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *JoinGroupReply) Reset() {
	*x = JoinGroupReply{}
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGroupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupReply) ProtoMessage() {}

func (x *JoinGroupReply) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupReply.ProtoReflect.Descriptor instead.
func (*JoinGroupReply) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_group_group_proto_rawDescGZIP(), []int{11}
}

func (x *JoinGroupReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LeaveGroupArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId int64 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
}

func (x *LeaveGroupArgs) Reset() {
	*x = LeaveGroupArgs{}
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGroupArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGroupArgs) ProtoMessage() {}

func (x *LeaveGroupArgs) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGroupArgs.ProtoReflect.Descriptor instead.
func (*LeaveGroupArgs) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_group_group_proto_rawDescGZIP(), []int{12}
}

func (x *LeaveGroupArgs) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LeaveGroupArgs) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type LeaveGroupReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *LeaveGroupReply) Reset() {
	*x = LeaveGroupReply{}
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGroupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGroupReply) ProtoMessage() {}

func (x *LeaveGroupReply) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGroupReply.ProtoReflect.Descriptor instead.
func (*LeaveGroupReply) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_group_group_proto_rawDescGZIP(), []int{13}
}

func (x *LeaveGroupReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetGroupHistoryArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId int64 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Cursor  int64 `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit   int64 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetGroupHistoryArgs) Reset() {
	*x = GetGroupHistoryArgs{}
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupHistoryArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupHistoryArgs) ProtoMessage() {}

func (x *GetGroupHistoryArgs) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupHistoryArgs.ProtoReflect.Descriptor instead.
func (*GetGroupHistoryArgs) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_group_group_proto_rawDescGZIP(), []int{14}
}

func (x *GetGroupHistoryArgs) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetGroupHistoryArgs) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *GetGroupHistoryArgs) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetGroupHistoryReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages   []*GroupMsgItem `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	NextCursor int64           `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore    bool            `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
}

func (x *GetGroupHistoryReply) Reset() {
	*x = GetGroupHistoryReply{}
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupHistoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupHistoryReply) ProtoMessage() {}

func (x *GetGroupHistoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupHistoryReply.ProtoReflect.Descriptor instead.
func (*GetGroupHistoryReply) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_group_group_proto_rawDescGZIP(), []int{15}
}

func (x *GetGroupHistoryReply) GetMessages() []*GroupMsgItem {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetGroupHistoryReply) GetNextCursor() int64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *GetGroupHistoryReply) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GroupMsgItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId      int64  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	SenderId   int64  `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Content    string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreateTime string `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
}

func (x *GroupMsgItem) Reset() {
	*x = GroupMsgItem{}
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMsgItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMsgItem) ProtoMessage() {}

func (x *GroupMsgItem) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMsgItem.ProtoReflect.Descriptor instead.
func (*GroupMsgItem) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_group_group_proto_rawDescGZIP(), []int{16}
}

func (x *GroupMsgItem) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *GroupMsgItem) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *GroupMsgItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GroupMsgItem) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type DissolveGroupArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId int64 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
}

func (x *DissolveGroupArgs) Reset() {
	*x = DissolveGroupArgs{}
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DissolveGroupArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DissolveGroupArgs) ProtoMessage() {}

func (x *DissolveGroupArgs) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DissolveGroupArgs.ProtoReflect.Descriptor instead.
func (*DissolveGroupArgs) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_group_group_proto_rawDescGZIP(), []int{17}
}

func (x *DissolveGroupArgs) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DissolveGroupArgs) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type DissolveGroupReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DissolveGroupReply) Reset() {
	*x = DissolveGroupReply{}
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DissolveGroupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DissolveGroupReply) ProtoMessage() {}

func (x *DissolveGroupReply) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pkg_proto_pb_group_group_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DissolveGroupReply.ProtoReflect.Descriptor instead.
func (*DissolveGroupReply) Descriptor() ([]byte, []int) {
	return file_apps_pkg_proto_pb_group_group_proto_rawDescGZIP(), []int{18}
}

func (x *DissolveGroupReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_apps_pkg_proto_pb_group_group_proto protoreflect.FileDescriptor

var file_apps_pkg_proto_pb_group_group_proto_rawDesc = []byte{
	0x0a, 0x23, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x70, 0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x22,
	0x68, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x72,
	0x67, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x09,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x73, 0x22, 0x2d, 0x0a, 0x10, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x19, 0x0a,
	0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x2b, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x67, 0x73, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x60, 0x0a, 0x09, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x22, 0x40, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2b, 0x0a, 0x06,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70,
	0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22, 0x2d, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x41, 0x72, 0x67, 0x73, 0x12, 0x19, 0x0a,
	0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x68, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x19, 0x0a,
	0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x30, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x41, 0x72, 0x67, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x64, 0x22, 0x5a, 0x0a, 0x0f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x72, 0x6f, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x4b, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x33, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x62, 0x5f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x43, 0x0a,
	0x0d, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x72, 0x67, 0x73, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x49, 0x64, 0x22, 0x2a, 0x0a, 0x0e, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x44,
	0x0a, 0x0e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x72, 0x67, 0x73,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x64, 0x22, 0x2b, 0x0a, 0x0f, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x22, 0x5e, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x41, 0x72, 0x67, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x22, 0x86, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x32, 0x0a, 0x08, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70,
	0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x73, 0x67,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1f,
	0x0a, 0x0b, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x6e, 0x65, 0x78, 0x74, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12,
	0x19, 0x0a, 0x08, 0x68, 0x61, 0x73, 0x5f, 0x6d, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x68, 0x61, 0x73, 0x4d, 0x6f, 0x72, 0x65, 0x22, 0x7d, 0x0a, 0x0c, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x4d, 0x73, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x73,
	0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x47, 0x0a, 0x11, 0x44, 0x69, 0x73,
	0x73, 0x6f, 0x6c, 0x76, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x72, 0x67, 0x73, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x49, 0x64, 0x22, 0x2e, 0x0a, 0x12, 0x44, 0x69, 0x73, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x32, 0xd9, 0x04, 0x0a, 0x0c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x1a, 0x2e,
	0x70, 0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x47, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x70, 0x62, 0x5f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73,
	0x74, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x1b, 0x2e, 0x70, 0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x47, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x1a, 0x2e, 0x70, 0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x47, 0x65,
	0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x1b,
	0x2e, 0x70, 0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x50, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x1d,
	0x2e, 0x70, 0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x1e, 0x2e,
	0x70, 0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3e, 0x0a,
	0x09, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x5f,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41,
	0x72, 0x67, 0x73, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x4a,
	0x6f, 0x69, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x41, 0x0a,
	0x0a, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x18, 0x2e, 0x70, 0x62,
	0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x2e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x50, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x12, 0x1d, 0x2e, 0x70, 0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x47,
	0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x41, 0x72,
	0x67, 0x73, 0x1a, 0x1e, 0x2e, 0x70, 0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x47, 0x65,
	0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x4a, 0x0a, 0x0d, 0x44, 0x69, 0x73, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x12, 0x1b, 0x2e, 0x70, 0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x44,
	0x69, 0x73, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x41, 0x72, 0x67, 0x73,
	0x1a, 0x1c, 0x2e, 0x70, 0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x44, 0x69, 0x73, 0x73,
	0x6f, 0x6c, 0x76, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x21,
	0x5a, 0x1f, 0x4e, 0x65, 0x78, 0x75, 0x73, 0x47, 0x6f, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x5f, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apps_pkg_proto_pb_group_group_proto_rawDescOnce sync.Once
	file_apps_pkg_proto_pb_group_group_proto_rawDescData = file_apps_pkg_proto_pb_group_group_proto_rawDesc
)

func file_apps_pkg_proto_pb_group_group_proto_rawDescGZIP() []byte {
	file_apps_pkg_proto_pb_group_group_proto_rawDescOnce.Do(func() {
		file_apps_pkg_proto_pb_group_group_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_pkg_proto_pb_group_group_proto_rawDescData)
	})
	return file_apps_pkg_proto_pb_group_group_proto_rawDescData
}

var file_apps_pkg_proto_pb_group_group_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_apps_pkg_proto_pb_group_group_proto_goTypes = []any{
	(*CreateGroupArgs)(nil),      // 0: pb_group.CreateGroupArgs
	(*CreateGroupReply)(nil),     // 1: pb_group.CreateGroupReply
	(*GetGroupListArgs)(nil),     // 2: pb_group.GetGroupListArgs
	(*GroupItem)(nil),            // 3: pb_group.GroupItem
	(*GetGroupListReply)(nil),    // 4: pb_group.GetGroupListReply
	(*GetGroupInfoArgs)(nil),     // 5: pb_group.GetGroupInfoArgs
	(*GetGroupInfoReply)(nil),    // 6: pb_group.GetGroupInfoReply
	(*GetGroupMembersArgs)(nil),  // 7: pb_group.GetGroupMembersArgs
	(*GroupMemberItem)(nil),      // 8: pb_group.GroupMemberItem
	(*GetGroupMembersReply)(nil), // 9: pb_group.GetGroupMembersReply
	(*JoinGroupArgs)(nil),        // 10: pb_group.JoinGroupArgs
	(*JoinGroupReply)(nil),       // 11: pb_group.JoinGroupReply
	(*LeaveGroupArgs)(nil),       // 12: pb_group.LeaveGroupArgs
	(*LeaveGroupReply)(nil),      // 13: pb_group.LeaveGroupReply
	(*GetGroupHistoryArgs)(nil),  // 14: pb_group.GetGroupHistoryArgs
	(*GetGroupHistoryReply)(nil), // 15: pb_group.GetGroupHistoryReply
	(*GroupMsgItem)(nil),         // 16: pb_group.GroupMsgItem
	(*DissolveGroupArgs)(nil),    // 17: pb_group.DissolveGroupArgs
	(*DissolveGroupReply)(nil),   // 18: pb_group.DissolveGroupReply
}
var file_apps_pkg_proto_pb_group_group_proto_depIdxs = []int32{
	3,  // 0: pb_group.GetGroupListReply.groups:type_name -> pb_group.GroupItem
	8,  // 1: pb_group.GetGroupMembersReply.members:type_name -> pb_group.GroupMemberItem
	16, // 2: pb_group.GetGroupHistoryReply.messages:type_name -> pb_group.GroupMsgItem
	0,  // 3: pb_group.GroupService.CreateGroup:input_type -> pb_group.CreateGroupArgs
	2,  // 4: pb_group.GroupService.GetGroupList:input_type -> pb_group.GetGroupListArgs
	5,  // 5: pb_group.GroupService.GetGroupInfo:input_type -> pb_group.GetGroupInfoArgs
	7,  // 6: pb_group.GroupService.GetGroupMembers:input_type -> pb_group.GetGroupMembersArgs
	10, // 7: pb_group.GroupService.JoinGroup:input_type -> pb_group.JoinGroupArgs
	12, // 8: pb_group.GroupService.LeaveGroup:input_type -> pb_group.LeaveGroupArgs
	14, // 9: pb_group.GroupService.GetGroupHistory:input_type -> pb_group.GetGroupHistoryArgs
	17, // 10: pb_group.GroupService.DissolveGroup:input_type -> pb_group.DissolveGroupArgs
	1,  // 11: pb_group.GroupService.CreateGroup:output_type -> pb_group.CreateGroupReply
	4,  // 12: pb_group.GroupService.GetGroupList:output_type -> pb_group.GetGroupListReply
	6,  // 13: pb_group.GroupService.GetGroupInfo:output_type -> pb_group.GetGroupInfoReply
	9,  // 14: pb_group.GroupService.GetGroupMembers:output_type -> pb_group.GetGroupMembersReply
	11, // 15: pb_group.GroupService.JoinGroup:output_type -> pb_group.JoinGroupReply
	13, // 16: pb_group.GroupService.LeaveGroup:output_type -> pb_group.LeaveGroupReply
	15, // 17: pb_group.GroupService.GetGroupHistory:output_type -> pb_group.GetGroupHistoryReply
	18, // 18: pb_group.GroupService.DissolveGroup:output_type -> pb_group.DissolveGroupReply
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_apps_pkg_proto_pb_group_group_proto_init() }
func file_apps_pkg_proto_pb_group_group_proto_init() {
	if File_apps_pkg_proto_pb_group_group_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_pkg_proto_pb_group_group_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_pkg_proto_pb_group_group_proto_goTypes,
		DependencyIndexes: file_apps_pkg_proto_pb_group_group_proto_depIdxs,
		MessageInfos:      file_apps_pkg_proto_pb_group_group_proto_msgTypes,
	}.Build()
	File_apps_pkg_proto_pb_group_group_proto = out.File
	file_apps_pkg_proto_pb_group_group_proto_rawDesc = nil
	file_apps_pkg_proto_pb_group_group_proto_goTypes = nil
	file_apps_pkg_proto_pb_group_group_proto_depIdxs = nil
}
